// Configuration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
open class Configuration {
    public var basePath: String
    public var apiKey: [String: String] = [:]

    public init(basePath: String) {
        self.basePath = basePath
    }

    public static var successfulStatusCodeRange: Range = 200..<300
}
