//
// ArchiveCandidate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArchiveCandidate: Codable, JSONEncodable, Hashable {

    public static let phoneRule = StringRule(minLength: nil, maxLength: 16, pattern: nil)
    public static let emailRule = StringRule(minLength: nil, maxLength: 254, pattern: nil)
    public var id: Int
    public var fullName: String
    public var updatedAt: Date
    public var bio: String
    public var photo: String?
    public var city: String
    public var phone: String
    public var email: String?
    public var cause: String

    public init(id: Int, fullName: String, updatedAt: Date, bio: String, photo: String? = nil, city: String, phone: String, email: String?, cause: String) {
        self.id = id
        self.fullName = fullName
        self.updatedAt = updatedAt
        self.bio = bio
        self.photo = photo
        self.city = city
        self.phone = phone
        self.email = email
        self.cause = cause
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case fullName = "full_name"
        case updatedAt = "updated_at"
        case bio
        case photo
        case city
        case phone
        case email
        case cause
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(fullName, forKey: .fullName)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(bio, forKey: .bio)
        try container.encodeIfPresent(photo, forKey: .photo)
        try container.encode(city, forKey: .city)
        try container.encode(phone, forKey: .phone)
        try container.encode(email, forKey: .email)
        try container.encode(cause, forKey: .cause)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ArchiveCandidate: Identifiable {}
