//
// Invitation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Invitation: Codable, JSONEncodable, Hashable {

    public var candidate: Int
    public var name: String
    public var surname: String
    public var patronymic: String
    public var city: String
    public var age: Int
    public var photo: String
    public var status: String
    public var updatedAt: String

    public init(candidate: Int, name: String, surname: String, patronymic: String, city: String, age: Int, photo: String, status: String, updatedAt: String) {
        self.candidate = candidate
        self.name = name
        self.surname = surname
        self.patronymic = patronymic
        self.city = city
        self.age = age
        self.photo = photo
        self.status = status
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case candidate
        case name
        case surname
        case patronymic
        case city
        case age
        case photo
        case status
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(candidate, forKey: .candidate)
        try container.encode(name, forKey: .name)
        try container.encode(surname, forKey: .surname)
        try container.encode(patronymic, forKey: .patronymic)
        try container.encode(city, forKey: .city)
        try container.encode(age, forKey: .age)
        try container.encode(photo, forKey: .photo)
        try container.encode(status, forKey: .status)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

