//
// MonthlyStatistic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MonthlyStatistic: Codable, JSONEncodable, Hashable {

    public var month: String
    public var issued: Int
    public var invited: Int
    public var accepted: Int
    public var rejected: Int
    public var subtracted: Int

    public init(month: String, issued: Int, invited: Int, accepted: Int, rejected: Int, subtracted: Int) {
        self.month = month
        self.issued = issued
        self.invited = invited
        self.accepted = accepted
        self.rejected = rejected
        self.subtracted = subtracted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case month
        case issued
        case invited
        case accepted
        case rejected
        case subtracted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(month, forKey: .month)
        try container.encode(issued, forKey: .issued)
        try container.encode(invited, forKey: .invited)
        try container.encode(accepted, forKey: .accepted)
        try container.encode(rejected, forKey: .rejected)
        try container.encode(subtracted, forKey: .subtracted)
    }
}

