//
// PatchedFavorite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedFavorite: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var candidate: Int?
    public var candidateInfo: CandidateInfo?
    public var createdAt: Date?

    public init(id: Int? = nil, candidate: Int? = nil, candidateInfo: CandidateInfo? = nil, createdAt: Date? = nil) {
        self.id = id
        self.candidate = candidate
        self.candidateInfo = candidateInfo
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case candidate
        case candidateInfo = "candidate_info"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(candidate, forKey: .candidate)
        try container.encodeIfPresent(candidateInfo, forKey: .candidateInfo)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedFavorite: Identifiable {}
