//
// PatchedSupervisor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedSupervisor: Codable, JSONEncodable, Hashable {

    public static let departmentRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public var id: Int?
    public var user: User?
    public var office: Int?
    public var officeName: String?
    public var department: String?

    public init(id: Int? = nil, user: User? = nil, office: Int? = nil, officeName: String? = nil, department: String? = nil) {
        self.id = id
        self.user = user
        self.office = office
        self.officeName = officeName
        self.department = department
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case office
        case officeName = "office_name"
        case department
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(office, forKey: .office)
        try container.encodeIfPresent(officeName, forKey: .officeName)
        try container.encodeIfPresent(department, forKey: .department)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedSupervisor: Identifiable {}
