//
// PatchedQuotaRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedQuotaRequest: Codable, JSONEncodable, Hashable {

    public static let amountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var office: Int?
    public var officeName: String?
    public var amount: Int?
    public var status: StatusA13Enum?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: Int? = nil, office: Int? = nil, officeName: String? = nil, amount: Int? = nil, status: StatusA13Enum? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.office = office
        self.officeName = officeName
        self.amount = amount
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case office
        case officeName = "office_name"
        case amount
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(office, forKey: .office)
        try container.encodeIfPresent(officeName, forKey: .officeName)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedQuotaRequest: Identifiable {}
