//
// QuotaRequestDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuotaRequestDetail: Codable, JSONEncodable, Hashable {

    public static let amountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int
    public var amount: Int
    public var createdAt: Date
    public var status: StatusA13Enum?
    public var officeInfo: Office
    public var history: String

    public init(id: Int, amount: Int, createdAt: Date, status: StatusA13Enum? = nil, officeInfo: Office, history: String) {
        self.id = id
        self.amount = amount
        self.createdAt = createdAt
        self.status = status
        self.officeInfo = officeInfo
        self.history = history
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case amount
        case createdAt = "created_at"
        case status
        case officeInfo = "office_info"
        case history
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(amount, forKey: .amount)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(officeInfo, forKey: .officeInfo)
        try container.encode(history, forKey: .history)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuotaRequestDetail: Identifiable {}
