//
// StatusA13Enum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;waited&#x60; - ожидание * &#x60;accepted&#x60; - Принято * &#x60;rejected&#x60; - Отклонено */
public enum StatusA13Enum: String, Codable, CaseIterable {
    case waited = "waited"
    case accepted = "accepted"
    case rejected = "rejected"
}
