//
// Status0d0Enum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;invited&#x60; - Приглашён * &#x60;accepted&#x60; - Принят * &#x60;rejected&#x60; - Отклонён * &#x60;self_rejected&#x60; - Отказ Кандидата */
public enum Status0d0Enum: String, Codable, CaseIterable {
    case invited = "invited"
    case accepted = "accepted"
    case rejected = "rejected"
    case selfRejected = "self_rejected"
}
