//
// Supervisor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Supervisor: Codable, JSONEncodable, Hashable {

    public static let departmentRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public var id: Int
    public var user: User
    public var office: Int?
    public var officeName: String
    public var department: String?

    public init(id: Int, user: User, office: Int?, officeName: String, department: String?) {
        self.id = id
        self.user = user
        self.office = office
        self.officeName = officeName
        self.department = department
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case office
        case officeName = "office_name"
        case department
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(user, forKey: .user)
        try container.encode(office, forKey: .office)
        try container.encode(officeName, forKey: .officeName)
        try container.encode(department, forKey: .department)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Supervisor: Identifiable {}
