//
// Todo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Todo: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var user: String
    public var task: String
    public var dueDate: Date
    public var isComplete: Bool?
    public var isDeleted: Bool?
    public var createdAt: Date

    public init(id: Int, user: String, task: String, dueDate: Date, isComplete: Bool? = nil, isDeleted: Bool? = nil, createdAt: Date) {
        self.id = id
        self.user = user
        self.task = task
        self.dueDate = dueDate
        self.isComplete = isComplete
        self.isDeleted = isDeleted
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case task
        case dueDate = "due_date"
        case isComplete = "is_complete"
        case isDeleted = "is_deleted"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(user, forKey: .user)
        try container.encode(task, forKey: .task)
        try container.encode(dueDate, forKey: .dueDate)
        try container.encodeIfPresent(isComplete, forKey: .isComplete)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Todo: Identifiable {}
